runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

service: default 

handlers:
- url: /househunt/static
  static_dir: static
- url: /.*
  script: run.app

skip_files:
  - ^\..*$

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  PROJECT: "zinc-bucksaw-245306"